### ISSUE TITLE
Add Loopback 4 example?

### ISSUE THREAD

**Issue by dougal83** [strongloop/loopback-example-kv-connectors#15]
Could Loopback 4 example be added?

See: https://github.com/strongloop/loopback-next/issues/4421

**Comment by hacksparrow** [comment]
Yes, we should.

**Comment by dhmlau** [comment]
Cross posting [comment](https://github.com/strongloop/loopback-next/issues/4421#issuecomment-574281752) from @jannyHou:

> Another usage can be found in loopback4-shopping-example: https://github.com/strongloop/loopback4-example-shopping/blob/master/packages/shopping/src/repositories/shopping-cart.repository.ts
> The shopping-cart repository is connected to a redis datasource.
